https://github.com/vishal2097/Vishal-Gawali

Name- Vishal Manoharrao Gawali
Reg No-20MAI0049

# Problem 2

# Implement Multi layer perceptron

In [25]:
import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler  
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

In [2]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [3]:
irisdata = pd.read_csv('iris.data', names=names)

In [20]:
irisdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal-length  150 non-null    float64
 1   sepal-width   150 non-null    float64
 2   petal-length  150 non-null    float64
 3   petal-width   150 non-null    float64
 4   Class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
print(irisdata)

     sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [5]:
# Takes first 4 columns and assign them to variable "X"
X = irisdata.iloc[:, 0:4]
# Takes first 5th columns and assign them to variable "Y". Object dtype refers to strings.
y = irisdata.select_dtypes(include=[object])

In [6]:
X.head()

sepal-length  sepal-width  petal-length  petal-width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [7]:
y.head

<bound method NDFrame.head of               Class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]>

In [8]:
y.Class.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [9]:
le = preprocessing.LabelEncoder()   #preprocess data and tranform into categorical form
y= y.apply(le.fit_transform)

In [21]:
y.Class.unique()       #display Unique datapoint of coloumn class

array([0, 1, 2])

In [10]:
y.head()

Class
0      0
1      0
2      0
3      0
4      0

In [11]:
X.head()

sepal-length  sepal-width  petal-length  petal-width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
#20% data of datset use for testing purpose remaining for training purpose

In [13]:
scaler  =StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test= scaler.transform(X_test) 

In [14]:
mlp = MLPClassifier(hidden_layer_sizes =(10,10,10), max_iter=1000)
mlp.fit(X_train, y_train.values.ravel())
#MLP classisifer use to train  modal

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

In [15]:
predictions = mlp.predict(X_test)

In [27]:
print(predictions)

[1 1 0 2 0 1 2 0 0 0 2 2 0 0 2 2 2 1 1 1 0 2 0 1 1 0 2 1 1 2]


In [19]:
print("Confusion Matrix\n",confusion_matrix(y_test, predictions))
print()
print("classification_report\n ",classification_report(y_test,predictions))

Confusion Matrix
 [[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]

classification_report
                precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      0.90      0.90        10
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



# conclusion

From confusion Matrix 10 Iris flower correctly classified as Iris-setosa,
9 Iris flower correctly classified as Iris-versicolor
but 1 Iris flower  predict as Iris-versicolor but actually it was Iris-virginica.
9 Iris flower correctly classified as Iris-virginica
but 1 Iris flower  predict as Iris-virginica but actually it was Iris-virginica.
